### ISSUE TITLE
Packing All proto3 Repeated Fields

### ISSUE THREAD

**Issue by mbgardner** [jeromegn/protobuf.cr#18]
It looks like the lib is attempting to pack all proto3 repeated fields rather than only scalar types.

_In proto3, repeated fields of scalar numeric types use packed encoding by default._

When presented with an invalid repeated field to pack, it's raising a type mismatch (Protobuf::Error) at runtime.

**Comment by jeromegn** [comment]
@packetzero thoughts?

**Comment by packetzero** [comment]
Hi mbgardner, can you post a couple of example .proto files that expose this issue?  I want to make sure I am understanding correctly.

**Comment by mbgardner** [comment]
Just to amend with more detail, if it's helpful:

```protobuf
message Foo {
  repeated Bar bar = 1; // this field shouldn't be packed
}

message Bar {
  string bar_field = 1;
}
```

I worked around the problem for now by checking if pb_type is truthy in #to_protobuf:

```crystal
{% if field[:repeated] %}
  {% if (pbVer != "proto2" && pb_type) || field[:packed] %}
  ...
```

**Comment by jeromegn** [comment]
@packetzero thanks for the fix!

@mbgardner I just merged a fix for this, can you confirm that this work with master?

**Comment by mbgardner** [comment]
I just plugged back into master and it's working for me. Thanks!

**Comment by packetzero** [comment]
You are welcome.  Thanks for taking the time to report it!
