### ISSUE TITLE
Add catch-all Protobuf::Exception class

### ISSUE THREAD

**Issue by Sija** [jeromegn/protobuf.cr#3]
First of all, let me say it's a piece of really nice work, I like especially the simplicity of the DSL and  modular approach used instead of inheritance :)

What do you think about creating a `Protobuf::Exception` class for easy catch-all?

**Comment by jeromegn** [comment]
Yes, that's a good idea!

**Comment by jeromegn** [comment]
I've added a `Protobuf::Error` class in `2.0.3` :)
