### ISSUE TITLE
Wont work with crystal 1.0

### ISSUE THREAD

**Issue by Jaciones** [jeromegn/protobuf.cr#37]
When trying to install the shard, the following error occurs.

crystal (< 1.0.0)` required by `protobuf 2.2.2...`

**Comment by jgaskins** [comment]
Oof, I thought I fixed this already, thanks for the heads up.

I went ahead and added a Crystal version restriction (the default is equivalent to `~> 0.1.0`, I believe) and [released version `2.2.3`](https://github.com/jeromegn/protobuf.cr/releases/tag/v2.2.3). If this doesn't fix the problem, feel free to re-open.
