### ISSUE TITLE
What about version 3?

### ISSUE THREAD

**Issue by MrSorcus** [jeromegn/protobuf.cr#4]
Or it's work only with version 2?

**Comment by jeromegn** [comment]
I haven't had a use for it and I'm a bit swamped to work on that version, unfortunately.

PR are definitely welcomed. I recognize this is quite a bit of work though ;)

**Comment by DebugReport** [comment]
I can't help with development, because I am not really good developer. Perhaps... X-)
Sorry :-(

**Comment by ltran** [comment]
@jeromegn Since you had a first stand at version 2, any place/docs would you recommend to get started?

**Comment by jeromegn** [comment]
@ltran if I remember correctly, I inspired a lot from ruby gems for protobuf. also, the spec from Google should help a lot.

https://developers.google.com/protocol-buffers/docs/proto3

I'm not entirely sure how different it is. It might not require huge changes.

**Comment by packetzero** [comment]
Main changes from v2 to v3:
 - no more required fields
 - no more default values
 - all repeating values are now in packed encoding
 
The current protobuf.cr will generate .pb.cr files for V3 .proto files.

If you manually add ",packed:true" to repeating fields in your generated .pb.cr files, you should be good to handle most V3 protobufs.  I at least verified the 4 simple examples given on the [Protobuf Encoding](https://developers.google.com/protocol-buffers/docs/encoding) doc page.

TODO:
 - recognize syntax="proto3" in .proto files and set flag in Message.
 - If Message.Version >= 3, default to packed:true
 - add more tests

**Comment by jeromegn** [comment]
I believe this is fixed with the 2.1.0 release. I've also updated the homebrew tap I maintain.
