### ISSUE TITLE
shard version

### ISSUE THREAD

**Issue by karlseguin** [jeromegn/protobuf.cr#6]
Might want to bump the shard version so people following the instructions get the latest. Particularly since MemoryIO no longer exists in 0.21.0.

In the meantime, anyone who runs into this could:

```
  protobuf:
    github: jeromegn/protobuf.cr
    commit: b9c556c
```

**Comment by jeromegn** [comment]
Done! Bumped to `2.0.4`

Thanks for pointing this out.
